server:
  #端口号
  port: 8888
#  max-http-header-size: 8999
  #项目名，如果不设定，默认是 /
  #context-path: /

# 连接his地址
hisUrl: http://172.9.10.42:10110

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/hl_fusong?useSSL=false
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:oracle:thin:@39.105.199.116:1521:orcl
    username: yufa
    password: yufa
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #url: jdbc:mysql://localhost:3306/hl_nmyy?useSSL=false
    #username: root
    #password: 123456
    #driver-class-name: com.mysql.jdbc.Driver
    platform: oracle
#    platform: mysql
#    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#    druid:
#      validation-query: select * from dual

#
  thymeleaf:
    cache: false #关闭缓存
    prefix: classpath:/ #添加路径前缀
#        view:
#            prefix: /
#            suffix: .jsp
    suffix: .html
    mode: HTML5
    content-type: text/html
    encoding: utf-8
#    html
#spring.thymeleaf.mode=HTML5
#spring.thymeleaf.encoding=UTF-8
#spring.thymeleaf.content-type=text/html

#  mvc:
#    view:
#        prefix: /
#        suffix: .jsp
#    static-path-pattern: /static/**


mybatis:
  configuration:
   map-underscore-to-camel-case: true #开启驼峰映射
   
logging:
  level:
   #打印SQL信息
   com.intehel.dao: debug
   org.springframework.web.servlet: info

   
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql
  
   
